replicaCount: 2

image:
  repository: 202291438766.dkr.ecr.us-east-1.amazonaws.com/eks-learning/argocluster
  pullPolicy: IfNotPresent

service:
  name: my-service
  type: NodePort
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
